import { CatalogItem, CatalogOption, CatalogPublicReview, CatalogPublicStats } from '../../../../interfaces/catalog';
import { ReadingStatusId } from '../../../../interfaces/read-status';
import { LibraryTextFilterChip, LibraryTextFilterScope, LibraryTextScopeOption } from '../../../../shared/library-search';

export interface MobileCatalogController {
    items: CatalogItem[];
    languages: CatalogOption[];
    styles: CatalogOption[];
    statusOptions: Array<{ Id: ReadingStatusId; Nombre: string; icon: string }>;
    isLoading: boolean;
    isSavingCollection: boolean;
    isLoadingPublicDetail: boolean;
    publicDetailLoadFailed: boolean;
    filterType: 'todos' | 'libro' | 'antologia';
    draftQuery: string;
    searchTerms: string[];
    textFilterChips: LibraryTextFilterChip[];
    textScopeOptions: LibraryTextScopeOption[];
    filtersOpen: boolean;
    hasActiveFilters: boolean;
    selectedStatusFilter: ReadingStatusId | '';
    selectedRatingFilter: number | '';
    selectedLanguageFilter: number | '';
    selectedStyleFilter: number | '';
    selectedDetailItem: CatalogItem | null;
    publicReviewPage: number;
    onDraftQueryInput(event: Event): void;
    commitDraftQuery(scope?: LibraryTextFilterScope): void;
    addTextFilter(scope: LibraryTextFilterScope, value: string): void;
    removeTextFilter(rawFilter: string): void;
    removeSearchTerm(term: string): void;
    clearFilters(): void;
    toggleFilters(): void;
    setTypeFilter(type: 'todos' | 'libro' | 'antologia'): void;
    applySelectFilters(): void;
    openItem(item: CatalogItem): void;
    closePublicDetailModal(): void;
    openNewRequest(type: 'libro' | 'antologia'): void;
    openCorrectionRequest(item: CatalogItem, event: MouseEvent): void;
    openCollectionModal(item: CatalogItem, event?: MouseEvent): void;
    addToCollectionWithStatus(item: CatalogItem, statusId: ReadingStatusId, event?: MouseEvent): void;
    openReadingFromDetail(): void;
    isInCollection(item: CatalogItem): boolean;
    isDetailInCollection(): boolean;
    authorsLabel(item: CatalogItem): string;
    languagesLabel(item: CatalogItem): string;
    stylesLabel(item: CatalogItem): string;
    latestStatusName(item: CatalogItem): string;
    statusClass(item: CatalogItem): string;
    statusIcon(item: CatalogItem): string;
    handleCoverImageError(event: Event): void;
    publicDetailTitle(): string;
    publicDetailAuthorsLabel(): string;
    publicDetailLanguagesLabel(): string;
    publicDetailStylesLabel(): string;
    publicDetailAverageRatingLabel(): string;
    publicDetailPersonalStatusName(): string;
    publicDetailPersonalRating(): number | null;
    publicDetailPersonalReview(): string;
    publicDetailStats(): CatalogPublicStats | null;
    pagedPublicReviewRows(): CatalogPublicReview[];
    publicReviewRows(): CatalogPublicReview[];
    publicReviewAuthorHandle(review: CatalogPublicReview): string;
    publicReviewDate(review: CatalogPublicReview): string | null;
    hasPublicReviewPages(): boolean;
    publicReviewTotalPages(): number;
    previousPublicReviewPage(): void;
    nextPublicReviewPage(): void;
}
